name: deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build Page
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avzO -e "ssh -p ${{ secrets.SSH_PORT }}" ./dist/ ubuntu@${{ secrets.SSH_HOST }}:/usr/share/nginx/html/
